export const FORM_ACTIONS = {
  CHANGE_VALUE: 'FORM.CHANGE_VALUE',
  VISIT: 'FORM.VISIT',
  FOCUS: 'FORM.FOCUS',
  CHANGE_STATUS: 'FORM.CHANGE_STATUS',
  SUBMIT: 'FORM.SUBMIT',
  RESET: 'FORM.RESET',
};
