export const ROUTER_STORE_ACTIONS = {
  STATE: 'ROUTER_STORE.STATE',
  PUSH: 'ROUTER_STORE.PUSH',
  REPLACE: 'ROUTER_STORE.REPLACE',
  BACK: 'ROUTER_STORE.BACK',
  GOTO: 'ROUTER_STORE.GOTO',
  FORWARD: 'ROUTER_STORE.FORWARD',
  BLOCK: 'ROUTER_STORE.BLOCK',
  CANCEL_BLOCK: 'ROUTER_STORE.CANCEL_BLOCK',
  RELOAD: 'ROUTER_STORE.RELOAD',
};

export const HISTORY_ACTIONS = {
  PUSH: 'HISTORY.PUSH',
  REPLACE: 'HISTORY.REPLACE',
  POP: 'HISTORY.POP',
};
